spring.application.name=lostfound
server.port=${PORT:8081}

spring.application.name=lostfound

spring.data.mongodb.uri=mongodb://localhost:27017/lostfound

jwt.secret=ThisIsMySecretKeyForLostAndFoundWebsite123456789

