spring.application.name=lostfound
server.port=${PORT:8081}
 

spring.data.mongodb.uri=mongodb+srv://ssafeeq2004_db_user:o37RnxU2vfDcTOsd@lost2found.r1degw9.mongodb.net/
jwt.secret=ThisIsMySecretKeyForLostAndFoundWebsite123456789



